### PR TITLE
Environment Variables Instructions issue #58

### LINKED ISSUE #58: Environment Variables Required on localhost!
If you `git clone git@github.com:dwyl/app-mvp-phoenix.git` and attempt to `mix deps.get` 
(_or any other mix command_) you will see the following error:
```
** (FunctionClauseError) no function clause matching in String.replace/4
```
image

Confusingly the error stack trace gives us _zero_ indication _where_ `String.replace/4` is being invoked so if you were a complete beginner trying to run this code you _definitely_ have a "WTF" moment!

This is because in [config/config.exs#L31-L35](https://github.com/dwyl/app-mvp-phoenix/blob/a7f57a1f0002d6f2b7c5a97ed1d01883e9a4779e/config/config.exs#L31-L35) the `ENCRYPTION_KEYS` environment variable is required:

https://github.com/dwyl/app-mvp-phoenix/blob/a7f57a1f0002d6f2b7c5a97ed1d01883e9a4779e/config/config.exs#L31-L35

This is actually invoking `String.replace/3` but if the `ENCRYPTION_KEYS` environment variable is not set, then `System.get_env("ENCRYPTION_KEYS")` will return `nil` which chokes the string replace. 

image

At present the [Run the app on `localhost`](https://github.com/dwyl/app-mvp-phoenix/tree/a7f57a1f0002d6f2b7c5a97ed1d01883e9a4779e#run-the-app-on-localhost) in the `README.md` is incomplete:
image
We need to provide people with more detailed instructions for getting the app running.
_specifically_ we need an `.env_sample` file with all the environment variables necessary for running the app on Localhost. Similar to [dwyl/elixir-auth-google-demo/**.env_sample**](https://github.com/dwyl/elixir-auth-google-demo/blob/master/.env_sample)

Furthermore given that we are using [`elixir_auth_google`](https://github.com/dwyl/elixir-auth-google) for Google Auth:
https://github.com/dwyl/app-mvp-phoenix/blob/a7f57a1f0002d6f2b7c5a97ed1d01883e9a4779e/mix.exs#L52
We _also_ need to have the Google `GOOGLE_CLIENT_ID` and `GOOGLE_CLIENT_SECRET` environment variables. This is not reflected in the `README.md` 🤷‍♂ 

# Todo

+ [x] Update instructions in `README.md` to include all required environment variables.

### PR DESCRIPTION
**Pull request by nelsonic**
+ [x] Update instructions for running the app on Localhost Fixes #58 
+ [x] Add `.env_sample` file with all necessary environment variables.
+ [x] Add link to Google App setup so people know how to create their API keys

### CODE REVIEW

File: lib/app_web/router.ex [hunk 1]
```diff
@@ -13,9 +13,11 @@ defmodule AppWeb.Router do
 
   pipeline :api do
     plug CORSPlug,
-      origin: System.get_env("ALLOW_API_ORIGINS")
-              |> String.replace("'", "")
-              |> String.split(",")
+      origin:
+        System.get_env("ALLOW_API_ORIGINS")
```
Comment (nelsonic) [inline lib/app_web/router.ex]: I don't think this should be an Environment Variable if we are just going to set it to **`*`** on Heroku ... 💭

File: test/app_web/controllers/capture_controller_test.exs [hunk 2]
```diff
@@ -22,9 +22,10 @@ defmodule AppWeb.CaptureControllerTest do
       assert redirected_to(conn) == Routes.categorise_path(conn, :index)
     end
 
-
     test "api - create a new capture", %{conn: conn} do
-      conn = post(conn, Routes.capture_path(conn, :api_create), item: @create_attrs)
+      conn =
+        post(conn, Routes.capture_path(conn, :api_create), item: @create_attrs)
```
Comment (nelsonic) [inline test/app_web/controllers/capture_controller_test.exs]: I didn't change anything here. this was `mix format` tidying up the code. 👍

**Comment by nelsonic** [comment]
@iteles these updated instructions will be relevant to you when you attempt to run the App on your `localhost` so I've requested review. 👍

File: lib/app_web/router.ex (hunk 1 above)
Comment (SimonLab) [reply lib/app_web/router.ex]: My thought for having it as an environment variable is that we could decide and remove quickly domain names that send request to the server. This could be a first way to filter unwanted request. However we can use also API keys.

Comment (nelsonic) [reply lib/app_web/router.ex]: @SimonLab the only way to avoid bad actors at an API level is having API keys. 
Having a "whitelist" or "blacklist" of domains is worthless because requests can be _spoofed_. 
IP address whitelisting is viable because it works at the TCP level. 
Let's not worry about this now. We can always refactor it later. 👍

File: README.md [hunk 3]
```diff
@@ -486,43 +486,84 @@ https://github.com/dwyl/app/issues/234
...
+
+Finally once everything is installed and the DB is created,
+run the app:
+
+```
+mix phx.server
+```
+
+Visit [`localhost:4000`](http://localhost:4000) in your web browser.
+You should see somethign similar to the following:
```
Comment (iteles) [inline README.md]:
```suggestion
You should see something similar to the following:
```

Comment (nelsonic) [reply README.md]: Tried to commit the suggested change but got a "Sorry ..." error message:
image
If you are going to make a suggestion, please don't then override it with your own commit. 👍

**Comment by nelsonic** [comment]
@iteles thanks for reviewing/merging. 👍
